from enum import StrEnum


class SharedErrorCode(StrEnum):
    VALIDATION_ERROR = "VALIDATION_ERROR"
    NOT_FOUND = "NOT_FOUND"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    METHOD_NOT_ALLOWED = "METHOD_NOT_ALLOWED"
    HTTP_ERROR = "HTTP_ERROR"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"


VALIDATION_ERROR_MESSAGE = "Request validation failed"
INTERNAL_SERVER_ERROR_MESSAGE = "An unexpected error occurred"
USER_NOT_FOUND_ERROR_MESSAGE = "User not found"